### ISSUE TITLE
cannot install api

### ISSUE THREAD

**Issue by Appmantx** [bakerframework/bakercloud-ce-console#20]
Hello Andrew, I have a problem with api installation. I made a video of the problem I am having. Thank You for all your hard work. https://www.youtube.com/watch?v=Z8chlVQCz_o

**Comment by nin9creative** [comment]
First off if it's not too late you may want to instead install the Baker Cloud Console (CE) version which is a newer version of MagRocket (now branded under the Baker umbrella).

You can find info and the download link here.  The install is basically the same as MagRocket.

http://www.bakerframework.com/bakercloudce/

With the error you are seeing.  I think it's because you might not have PHP 5.3 or greater installed on your hosting account.  Typically errors that are complaining about that SLIM loader line are complaining because of the PHP version.

First thing would be to check which PHP version is installed.  A quick way to do this is to create a .php file and upload it to your server.

Just put this in the file itself (name it something like info.php), upload it and browse to it.  It should give you a bunch of info which then you can post back here.

```
<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>
```

Actually to make is simpler, you can just use this file.

https://dl.dropboxusercontent.com/u/14238775/Baker/info.php

**Comment by nin9creative** [comment]
From our prior conversations it seems you are past this point.  Closing issue.
