### ISSUE TITLE
Subscription not expiring (tested in sandbox mode)

### ISSUE THREAD

**Issue by theBrandonWu** [bakerframework/bakercloud-ce-console#22]
I am testing this in sandbox mode with a test account and I had access to all issues even after the subscription has expired. 

![subscriptions management](https://f.cloud.github.com/assets/4529176/2220242/266c7190-9a4b-11e3-81f9-14485da2506a.jpg)

The subscription auto-renewed for 5 times (see screenshot of Receipts Management) but the last renewal should have expired a few days ago as well.

![receipts management](https://f.cloud.github.com/assets/4529176/2220269/81d21b7a-9a4b-11e3-9a6d-e8b50ccf9279.jpg)

Is anyone else seeing this? Thanks!

**Comment by nin9creative** [comment]
You need to understand how the Subscription unlocking process works, plus there are some caveats when testing in Sandbox.

1)  A subscription being valid does two things a) shows if you are subscribed/unsubscribed in the Subscription popover in Baker and b) determines which items are added to the Purchases table

2)  Issues are unlocked for a user that has a Subscription and added to the Purchases table.  If a Subscription expires, Issues that were available to them during the term of their Subscription are still available to the user.  They don't just dissapear.  Once they are in the Purchases table, they are available whether the Subscription is still valid or not.

3)  Issues are queried based on their release date when being considered in logic for adding to the Purchases table by the API.  Since the Sandbox uses accelerated time, during Sandbox mode the API just unlocks ALL issues, regardless if they are within the timeframe or not - for testing.

If you need further details, you can browse through the logic within the ConfirmPurchase and Purchases endpoints in the API to see what all the conditions are.

However Sandbox behaves differently than Production because of the accelerated time reasons.

**Comment by theBrandonWu** [comment]
Got it. I missed this point:

> 2) Issues are unlocked for a user that has a Subscription and added to the Purchases table. If a Subscription expires, Issues that were available to them during the term of their Subscription are still available to the user.

Thanks again Andrew!
