### ISSUE TITLE
Json format for Amazon SNS

### ISSUE THREAD

**Issue by fobetor** [bakerframework/bakercloud-ce-console#25]
Hello
I still havent had time to implement the php code for push notifications from baker, but as Andrew said, from Amazon it can be done. Now I'm doing so "by hand" from amazon interface.
BUT... I'm having problems to send messages as in the wiki intructions:
{
"aps": {
"content-available": 1
},
"content-name": "a-study-in-scarlet"
}

I cant figure out how to format this in the amazon json interface so it works.
I can send informative messages, but no way to give the correct json format to make bakgroud updates/downloads.
 The issue is about the formatting for the amazon interface.

Any help?

Thank you

**Comment by nin9creative** [comment]
Sorry, just saw this now.  Are you still having this problem?

**Comment by fobetor** [comment]
yes andrew. i think its about escsping cuotes etc, but i cant make the correct formatting.

**Comment by fobetor** [comment]
i cant find an online formatting tool. thank you

**Comment by nin9creative** [comment]
I haven't tested this, but went into the Amazon SNS interface to send a test message.

This is the default that they give you when you want to send a normal message.

```
{
 "APNS_SANDBOX":"{\"aps\":{\"alert\":\"<message>\"}}"
}
```

![sns_management_console](https://f.cloud.github.com/assets/449883/2301805/c17a6f68-a15b-11e3-9ceb-625a5e987de8.jpg)

So what if you do something like this?

```
{
 "APNS_SANDBOX":"{\"aps\":{\"content-available\":1,\"content-name\":\"a-study-in-scarlet\"} }"
}
```

**Comment by fobetor** [comment]
I will try later and tell you the results
Thank you very much

**Comment by fobetor** [comment]
Well... at least amazon seems to send it, but I dont see any response from baker in my ipad. I mean, it does not download the issue I tell in the json or refresh the bookshelf.
The normal messages in text format works correctly to show notifications.
I dont find why it does not refresh the baker shelf

**Comment by nin9creative** [comment]
Is the app running in the background (i.e. not active)?

Andrew

**Comment by fobetor** [comment]
It is running, but not visible. For instance, i was trying this with the ipad "locked". I have just tested sending a general message 
{
 "APNS":"{\"aps\":{\"content-available\":1} }"
}
to refresh shelf, but.. no signs of responding

**Comment by nacho-marin** [comment]
If you carefully check the examples, as provided by nin9creative, they are not valid JSON... but they work.  See the APNS_SANDBOX key's value: it is "like" a JSON object, but the opening curly bracket is preceded with a comma and the closing one is followed by a comma. Thus, it is not a JSON object, it is a string.

So Amazon have defined their own "JSON", using some sort of "stringification" of the values of first level JSON keys. As values are strings, in order to interpret the strings, you have to scape values, and even numeric values must be string. If you do not do this, the AWS SNS console will send the message and will report success (and the AWS SDK too! -at least the JavaScript SDK, which is the one I tested) but it will not be actually sent. Pitiful!

For instance, in your first example, you did what every developer will initially do: use valid JSON. In your last example, following nin9creative recommendations, you surrounded the value for APNS key with quotes, but you forgot to set the value for content-available as \"1\" . Try this and it should work.

Oh, and if you are in a dev environment, perhaps you should use APNS_SANDBOX instead of APNS.
