### ISSUE TITLE
Using the pending feature in magrocket.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/bakercloud-ce-console#29]
Hi, i am trying to find a way to test out our issue content before publishing it to the public. Is using the pending feature in magrocket the way to do it? What does this feature do?

**Comment by nin9creative** [comment]
Pending just means that it doesn't show up on the shelf.

I had intentions for a future release of the Baker Cloud CE (coupled with Baker sending the Environment parameter) to show pending issues as well - as it would know that the device was connecting via a non production binary.

Another solution to this is to simply duplicate the /Issues method in the API and call it something like /IssuesTest

Then simply change the SQL query to return all Issues instead of just the 'published' issues.  Then you can point your test version of your binary at that endpoint and be able to view the issues that are not yet published, and test them out.

Andrew
